dist: bionic
install:
  - tmux -V
  - nvm install 10
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  - rustup toolchain install stable
  - ./scripts/prepare-end2end-tests.sh
script:
  - cargo test --verbose --no-fail-fast
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: target/shields
  on:
    branch: master
