# such config, much build...
dist: bionic
language: minimal
install:
  - tmux -V
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=stable --default-host=x86_64-unknown-linux-gnu -y
  - source $HOME/.cargo/env
  - rustup toolchain install nightly
  - nvm install 10
  - ./scripts/prepare-end2end-tests.sh
env:
  - RUST_CHAIN=stable
  - RUST_CHAIN=nightly
script:
  - rustup default $RUST_CHAIN
  - cargo build --all-targets
  # only run the tests, do not fail build when a test fails
  - cargo test --no-fail-fast || true
  # create badge for `cargo test`
  - >
      cargo test --no-fail-fast -- -Z unstable-options --format json | jq -s '{ "passed": map(select(.type == "suite" and has("passed")) | .passed) | add, "total": map(select(.type == "suite" and has("test_count")) | .test_count) | add } | . + { "factor": (.passed / .total) } | { "color": (if .factor < 0.33 then "red" elif .factor < 0.66 then "orange" elif .factor < 1.0 then "yellow" else "brightgreen" end), "isError": true, "label": "cargo test", "message": "\(.passed) / \(.total) tests", "schemaVersion": 1 }' > ./target/shields/cargo-test.json
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: target/shields
  on:
    branch: master
    condition: $RUST_CHAIN = stable
# It was time for Thomas to leave. He has seen everything...
#  - Thank you for travising with Deutsche Builds
