dist: bionic
language: rust
rust:
  - stable
  - nightly
addons:
  apt:
    update: true
    packages:
      - tmux
      - libevent-dev
install:
  - tmux -V
  - nvm install 10
  - ./scripts/prepare-end2end-tests.sh
script:
  - cargo test --verbose --no-fail-fast
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: target/shields
  on:
    branch: master
