# such config, much build...
dist: bionic
language: minimal
install:
  # tmux version should be >=2.6
  - tmux -V
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=stable --default-host=x86_64-unknown-linux-gnu -y
  - source $HOME/.cargo/env
  - rustup toolchain install nightly
  - nvm install 10
  - ./scripts/prepare-end2end-tests.sh
env:
  - RUST_CHAIN=stable
  - RUST_CHAIN=nightly
script:
  - rustup default $RUST_CHAIN
  - ./scripts/ci-build.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: target/shields
  verbose: true
  on:
    branch: master
# It was time for Thomas to leave. He has seen everything...
#  - Thank you for travising with Deutsche Builds
