language: rust
rust:
  - nightly

install:
  - nvm install 10
  - ./scripts/prepare-end2end-tests.sh
  - apt update
  - apt install tmux

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: target/shields
  on:
    branch: master
