[package]
name = "cursive-multiplex"
version = "0.2.11-alpha.0"
authors = ["Fin Christensen <christensen.fin@gmail.com>", "Johannes Wünsche <johannes.wuensche97@gmail.com>"]
edition = "2018"
description = "A tmux like multiplexer for gyscos/cursive views"
license = "BSD-3-Clause"
readme = "README.md"
keywords = ["cursive", "tui", "terminal", "tiling", "view"]
repository = "https://github.com/deinstapel/cursive-multiplex"
documentation = "https://docs.rs/cursive-multiplex"

[dependencies]
cursive = "0.13.0"
indextree = "4.0.0"
failure = "0.1.5"
failure_derive = "0.1.5"
log = "0.4.8"

[dev-dependencies]
serde_json = "1.0.40"

[badges]
travis-ci = { repository = "deinstapel/cursive-multiplex" }
