[package]
name = "cursive-multiplex"
version = "0.1.0"
authors = ["Johannes Wünsche <johannes.wuensche97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.12.0"
indextree = "3.2.0"
serde_json = "1.0.40"
failure = "0.1.5"
failure_derive = "0.1.5"
